// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChartsUIClient is the client API for ChartsUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChartsUIClient interface {
	// ListDocumentSpecs returns a list of Document that can be started through the UI.
	ListDocumentSpecs(ctx context.Context, in *ListDocumentSpecsRequest, opts ...grpc.CallOption) (ChartsUI_ListDocumentSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type chartsUIClient struct {
	cc grpc.ClientConnInterface
}

func NewChartsUIClient(cc grpc.ClientConnInterface) ChartsUIClient {
	return &chartsUIClient{cc}
}

func (c *chartsUIClient) ListDocumentSpecs(ctx context.Context, in *ListDocumentSpecsRequest, opts ...grpc.CallOption) (ChartsUI_ListDocumentSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChartsUI_ServiceDesc.Streams[0], "/v1.ChartsUI/ListDocumentSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &chartsUIListDocumentSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChartsUI_ListDocumentSpecsClient interface {
	Recv() (*ListDocumentSpecsResponse, error)
	grpc.ClientStream
}

type chartsUIListDocumentSpecsClient struct {
	grpc.ClientStream
}

func (x *chartsUIListDocumentSpecsClient) Recv() (*ListDocumentSpecsResponse, error) {
	m := new(ListDocumentSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chartsUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ChartsUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChartsUIServer is the server API for ChartsUI service.
// All implementations must embed UnimplementedChartsUIServer
// for forward compatibility
type ChartsUIServer interface {
	// ListDocumentSpecs returns a list of Document that can be started through the UI.
	ListDocumentSpecs(*ListDocumentSpecsRequest, ChartsUI_ListDocumentSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedChartsUIServer()
}

// UnimplementedChartsUIServer must be embedded to have forward compatible implementations.
type UnimplementedChartsUIServer struct {
}

func (UnimplementedChartsUIServer) ListDocumentSpecs(*ListDocumentSpecsRequest, ChartsUI_ListDocumentSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListDocumentSpecs not implemented")
}
func (UnimplementedChartsUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedChartsUIServer) mustEmbedUnimplementedChartsUIServer() {}

// UnsafeChartsUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChartsUIServer will
// result in compilation errors.
type UnsafeChartsUIServer interface {
	mustEmbedUnimplementedChartsUIServer()
}

func RegisterChartsUIServer(s grpc.ServiceRegistrar, srv ChartsUIServer) {
	s.RegisterService(&ChartsUI_ServiceDesc, srv)
}

func _ChartsUI_ListDocumentSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDocumentSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChartsUIServer).ListDocumentSpecs(m, &chartsUIListDocumentSpecsServer{stream})
}

type ChartsUI_ListDocumentSpecsServer interface {
	Send(*ListDocumentSpecsResponse) error
	grpc.ServerStream
}

type chartsUIListDocumentSpecsServer struct {
	grpc.ServerStream
}

func (x *chartsUIListDocumentSpecsServer) Send(m *ListDocumentSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ChartsUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChartsUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ChartsUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChartsUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChartsUI_ServiceDesc is the grpc.ServiceDesc for ChartsUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChartsUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ChartsUI",
	HandlerType: (*ChartsUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ChartsUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDocumentSpecs",
			Handler:       _ChartsUI_ListDocumentSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "charts-ui.proto",
}
