// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChartsServiceClient is the client API for ChartsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChartsServiceClient interface {
	// StartLocalDocument starts a Chart Document on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the charts/config.yaml
	//   3. all bytes constituting the Document YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalDocument(ctx context.Context, opts ...grpc.CallOption) (ChartsService_StartLocalDocumentClient, error)
	// StartFromPreviousDocument starts a new Document based on a previous one.
	// If the previous Document does not have the can-replay condition set this call will result in an error.
	StartFromPreviousDocument(ctx context.Context, in *StartFromPreviousDocumentRequest, opts ...grpc.CallOption) (*StartDocumentResponse, error)
	// StartDocumentRequest starts a new Document based on its specification.
	StartDocument(ctx context.Context, in *StartDocumentRequest, opts ...grpc.CallOption) (*StartDocumentResponse, error)
	// Searches for Document known to this instance
	ListDocument(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (*ListDocumentResponse, error)
	// Subscribe listens to new Document updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (ChartsService_SubscribeClient, error)
	// GetDocument retrieves details of a single Document
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	// Listen listens to Document updates and log output of a running Document
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (ChartsService_ListenClient, error)
	// StopDocument stops a currently running Document
	StopDocument(ctx context.Context, in *StopDocumentRequest, opts ...grpc.CallOption) (*StopDocumentResponse, error)
}

type chartsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChartsServiceClient(cc grpc.ClientConnInterface) ChartsServiceClient {
	return &chartsServiceClient{cc}
}

func (c *chartsServiceClient) StartLocalDocument(ctx context.Context, opts ...grpc.CallOption) (ChartsService_StartLocalDocumentClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChartsService_ServiceDesc.Streams[0], "/v1.ChartsService/StartLocalDocument", opts...)
	if err != nil {
		return nil, err
	}
	x := &chartsServiceStartLocalDocumentClient{stream}
	return x, nil
}

type ChartsService_StartLocalDocumentClient interface {
	Send(*StartLocalDocumentRequest) error
	CloseAndRecv() (*StartDocumentResponse, error)
	grpc.ClientStream
}

type chartsServiceStartLocalDocumentClient struct {
	grpc.ClientStream
}

func (x *chartsServiceStartLocalDocumentClient) Send(m *StartLocalDocumentRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chartsServiceStartLocalDocumentClient) CloseAndRecv() (*StartDocumentResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartDocumentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chartsServiceClient) StartFromPreviousDocument(ctx context.Context, in *StartFromPreviousDocumentRequest, opts ...grpc.CallOption) (*StartDocumentResponse, error) {
	out := new(StartDocumentResponse)
	err := c.cc.Invoke(ctx, "/v1.ChartsService/StartFromPreviousDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chartsServiceClient) StartDocument(ctx context.Context, in *StartDocumentRequest, opts ...grpc.CallOption) (*StartDocumentResponse, error) {
	out := new(StartDocumentResponse)
	err := c.cc.Invoke(ctx, "/v1.ChartsService/StartDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chartsServiceClient) ListDocument(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (*ListDocumentResponse, error) {
	out := new(ListDocumentResponse)
	err := c.cc.Invoke(ctx, "/v1.ChartsService/ListDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chartsServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (ChartsService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChartsService_ServiceDesc.Streams[1], "/v1.ChartsService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &chartsServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChartsService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type chartsServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *chartsServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chartsServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, "/v1.ChartsService/GetDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chartsServiceClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (ChartsService_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChartsService_ServiceDesc.Streams[2], "/v1.ChartsService/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &chartsServiceListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChartsService_ListenClient interface {
	Recv() (*ListenResponse, error)
	grpc.ClientStream
}

type chartsServiceListenClient struct {
	grpc.ClientStream
}

func (x *chartsServiceListenClient) Recv() (*ListenResponse, error) {
	m := new(ListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chartsServiceClient) StopDocument(ctx context.Context, in *StopDocumentRequest, opts ...grpc.CallOption) (*StopDocumentResponse, error) {
	out := new(StopDocumentResponse)
	err := c.cc.Invoke(ctx, "/v1.ChartsService/StopDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChartsServiceServer is the server API for ChartsService service.
// All implementations must embed UnimplementedChartsServiceServer
// for forward compatibility
type ChartsServiceServer interface {
	// StartLocalDocument starts a Chart Document on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the charts/config.yaml
	//   3. all bytes constituting the Document YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalDocument(ChartsService_StartLocalDocumentServer) error
	// StartFromPreviousDocument starts a new Document based on a previous one.
	// If the previous Document does not have the can-replay condition set this call will result in an error.
	StartFromPreviousDocument(context.Context, *StartFromPreviousDocumentRequest) (*StartDocumentResponse, error)
	// StartDocumentRequest starts a new Document based on its specification.
	StartDocument(context.Context, *StartDocumentRequest) (*StartDocumentResponse, error)
	// Searches for Document known to this instance
	ListDocument(context.Context, *ListDocumentRequest) (*ListDocumentResponse, error)
	// Subscribe listens to new Document updates
	Subscribe(*SubscribeRequest, ChartsService_SubscribeServer) error
	// GetDocument retrieves details of a single Document
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	// Listen listens to Document updates and log output of a running Document
	Listen(*ListenRequest, ChartsService_ListenServer) error
	// StopDocument stops a currently running Document
	StopDocument(context.Context, *StopDocumentRequest) (*StopDocumentResponse, error)
	mustEmbedUnimplementedChartsServiceServer()
}

// UnimplementedChartsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChartsServiceServer struct {
}

func (UnimplementedChartsServiceServer) StartLocalDocument(ChartsService_StartLocalDocumentServer) error {
	return status.Errorf(codes.Unimplemented, "method StartLocalDocument not implemented")
}
func (UnimplementedChartsServiceServer) StartFromPreviousDocument(context.Context, *StartFromPreviousDocumentRequest) (*StartDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFromPreviousDocument not implemented")
}
func (UnimplementedChartsServiceServer) StartDocument(context.Context, *StartDocumentRequest) (*StartDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDocument not implemented")
}
func (UnimplementedChartsServiceServer) ListDocument(context.Context, *ListDocumentRequest) (*ListDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocument not implemented")
}
func (UnimplementedChartsServiceServer) Subscribe(*SubscribeRequest, ChartsService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedChartsServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedChartsServiceServer) Listen(*ListenRequest, ChartsService_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedChartsServiceServer) StopDocument(context.Context, *StopDocumentRequest) (*StopDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopDocument not implemented")
}
func (UnimplementedChartsServiceServer) mustEmbedUnimplementedChartsServiceServer() {}

// UnsafeChartsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChartsServiceServer will
// result in compilation errors.
type UnsafeChartsServiceServer interface {
	mustEmbedUnimplementedChartsServiceServer()
}

func RegisterChartsServiceServer(s grpc.ServiceRegistrar, srv ChartsServiceServer) {
	s.RegisterService(&ChartsService_ServiceDesc, srv)
}

func _ChartsService_StartLocalDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChartsServiceServer).StartLocalDocument(&chartsServiceStartLocalDocumentServer{stream})
}

type ChartsService_StartLocalDocumentServer interface {
	SendAndClose(*StartDocumentResponse) error
	Recv() (*StartLocalDocumentRequest, error)
	grpc.ServerStream
}

type chartsServiceStartLocalDocumentServer struct {
	grpc.ServerStream
}

func (x *chartsServiceStartLocalDocumentServer) SendAndClose(m *StartDocumentResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chartsServiceStartLocalDocumentServer) Recv() (*StartLocalDocumentRequest, error) {
	m := new(StartLocalDocumentRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChartsService_StartFromPreviousDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFromPreviousDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChartsServiceServer).StartFromPreviousDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ChartsService/StartFromPreviousDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChartsServiceServer).StartFromPreviousDocument(ctx, req.(*StartFromPreviousDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChartsService_StartDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChartsServiceServer).StartDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ChartsService/StartDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChartsServiceServer).StartDocument(ctx, req.(*StartDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChartsService_ListDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChartsServiceServer).ListDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ChartsService/ListDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChartsServiceServer).ListDocument(ctx, req.(*ListDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChartsService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChartsServiceServer).Subscribe(m, &chartsServiceSubscribeServer{stream})
}

type ChartsService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type chartsServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *chartsServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ChartsService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChartsServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ChartsService/GetDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChartsServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChartsService_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChartsServiceServer).Listen(m, &chartsServiceListenServer{stream})
}

type ChartsService_ListenServer interface {
	Send(*ListenResponse) error
	grpc.ServerStream
}

type chartsServiceListenServer struct {
	grpc.ServerStream
}

func (x *chartsServiceListenServer) Send(m *ListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ChartsService_StopDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChartsServiceServer).StopDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ChartsService/StopDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChartsServiceServer).StopDocument(ctx, req.(*StopDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChartsService_ServiceDesc is the grpc.ServiceDesc for ChartsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChartsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ChartsService",
	HandlerType: (*ChartsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFromPreviousDocument",
			Handler:    _ChartsService_StartFromPreviousDocument_Handler,
		},
		{
			MethodName: "StartDocument",
			Handler:    _ChartsService_StartDocument_Handler,
		},
		{
			MethodName: "ListDocument",
			Handler:    _ChartsService_ListDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _ChartsService_GetDocument_Handler,
		},
		{
			MethodName: "StopDocument",
			Handler:    _ChartsService_StopDocument_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartLocalDocument",
			Handler:       _ChartsService_StartLocalDocument_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _ChartsService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _ChartsService_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "charts.proto",
}
